<a href="https://colab.research.google.com/github/arifanwar0243/colabs/blob/main/BackPropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

# Each row is a training example, each column is a feature [X1, X2, X3]
X = np.array(([0,0,1],[0,1,1],[1,0,1],[1,1,1]), dtype=float)
y = np.array(([0],[1],[1],[0]), dtype=float)

# Define useful functions

# Activation function
def sigmoid(z):
    return 1/(1+np.exp(-z))

# Derivative of sigmoid
def sigmoid_derivative(z):
    return z*(1-z)

# Class definition
class NeuralNetwork:
    def __init__(self, x, y, nNode):
        self.input = x
        print("Input data dimension =", self.input.shape)
        self.weights1 = np.random.rand(self.input.shape[1],nNode)
        print("Hidden layer weights dimension =", self.weights1.shape)
        # considering we have 4 nodes in the hidden layer
        self.weights2 = np.random.rand(nNode,1)
        print("Output layer weights dimension =", self.weights2.shape)
        self.y = y
        print("y dimension =", self.y.shape)
        self.output = np.zeros(self.y.shape)
        print("Derivative dimension 2 =", sigmoid_derivative(self.output).shape)
    
    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        print("Dimension of o1 =", self.layer1.shape)
        print("Derivative of o1 =", sigmoid_derivative(self.layer1).shape)
        self.layer2 = sigmoid(np.dot(self.layer1, self.weights2))
        print("Dimension of o2 =", self.layer2.shape)
        return self.layer2
    
    def backprop(self):
        d_weights2 = np.dot(self.layer1.T, 2*(self.y - self.output)*
                            sigmoid_derivative(self.output))
        d_weights1 = np.dot(self.input.T, np.dot(2*(self.y - self.output)*
                                                 sigmoid_derivative(self.output), self.weights2.T) * sigmoid_derivative(self.layer1))
        self.weights1 += d_weights1
        self.weights2 += d_weights2
    def train(self,X,y):
        self.output = self.feedforward()
        self.backprop()
hiddenLayerNode = 5
NN = NeuralNetwork(X,y,hiddenLayerNode)
for i in range(10):
  if i%750 == 0: 
    print('for iteration #'+str(i)+'\n')
    print('input :\n'+str(X))
    print('Actual output : \n'+str(y))
    print('Predicted Output :\n' + str(NN.feedforward))
    print('Loss :\n'+str(np.mean(np.square(y-NN.feedforward()))))
    print('\n')
  NN.train(X,y)


Input data dimension = (4, 3)
Hidden layer weights dimension = (3, 5)
Output layer weights dimension = (5, 1)
y dimension = (4, 1)
Derivative dimension 2 = (4, 1)
for iteration #0

input :
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual output : 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output :
<bound method NeuralNetwork.feedforward of <__main__.NeuralNetwork object at 0x7f6906d674f0>>
Dimension of o1 = (4, 5)
Derivative of o1 = (4, 5)
Dimension of o2 = (4, 1)
Loss :
0.40734009878458965


Dimension of o1 = (4, 5)
Derivative of o1 = (4, 5)
Dimension of o2 = (4, 1)
Dimension of o1 = (4, 5)
Derivative of o1 = (4, 5)
Dimension of o2 = (4, 1)
Dimension of o1 = (4, 5)
Derivative of o1 = (4, 5)
Dimension of o2 = (4, 1)
Dimension of o1 = (4, 5)
Derivative of o1 = (4, 5)
Dimension of o2 = (4, 1)
Dimension of o1 = (4, 5)
Derivative of o1 = (4, 5)
Dimension of o2 = (4, 1)
Dimension of o1 = (4, 5)
Derivative of o1 = (4, 5)
Dimension of o2 = (4, 1)
Dimension of o1 = (4, 5)
Derivative of o1 = (4